#!/usr/bin/env bash
# this willl Configures a new ubuntu machine by installing
# the Nginx  should be listening on port 80
# Serve a page that would return a Hello World string


echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# this will start nginx service
sudo service nginx start

# this will allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# this Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# this Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# this will Create new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

#this will Restart nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"

