#!/usr/bin/env bash
# installing the  load balancer


echo -e "Updating and doing some minor checks...\n"

function install() {
	command -v "$1" &> /dev/null

	#the shellcheck will  disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "	Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

install haproxy #install haproxy

echo -e "\nSetting up some minor stuff.\n"

#this will  backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend sabimaru-tech-frontend
    bind *:80
    default_backend sabimaru-tech-backend

backend subimaru-tech-backend
    balance roundrobin
    server 333350-web-01 54.144.135.252:80 check
    server 333350-web-02 35.153.79.155:80 check
"

# the shellcheck will disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

#this will  enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "configured - Roundrobin On web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi

echo -e "web-01 web-02"
echo "web-01"
echo "web-02"
