#!/usr/bin/env bash
#a Bash script that configures a server to the and listening on port 80 of all the server’s active IPv4 IPs

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
