#!/usr/bin/env bash
#a Bash script that configures a server to the and listening on port 80 of all the server’s active IPv4 IPs

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
