#!/usr/bin/env bash
# a Bash script that displays Best School 10 times.

for ((i=1; i<=10; i++))
do
    echo "Best School"
done

2-while_best_school
#!/usr/bin/env bash
#a Bash script that displays Best School 10 times.
counter=0
while [ $counter -lt 10 ]
do
    echo "Best School"
    ((counter++))
done
