#!/usr/bin/env bash
#this will Fix the server bugs

chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2

#this will  restart nginx service

su nginx -s /bin/bash -c 'service nginx restart'
